version: '3.8'

services:
  analytics-service:
    image: sha2121/shophub-analytics:amd-v1
    container_name: analytics_service
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: analytics
      RABBIT_URL: amqp://rabbitmq
    ports:
      - "3004:3004"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - shophub_network
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shophub
      MYSQL_USER: shophub_user
      MYSQL_PASSWORD: shophub_pass
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./analytics.sql:/docker-entrypoint-initdb.d/analytics.sql
      - mysql_data:/var/lib/mysql
    networks:
      - shophub_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shophub_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shophub_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
     RABBITMQ_DEFAULT_USER: guest
     RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shophub_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  landing-service:
    image: sha2121/shophub-landing-page:amd-v1
    container_name: landing-page
    restart: unless-stopped
    environment:
      PORT: 3000
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: shophub
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - shophub_network

  catalog-service:
    image: sha2121/shophub-catalog:amd-v1
    container_name: shophub_catalog
    restart: unless-stopped
    environment:
      PORT: 3001
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - shophub_network

  cart-service:
    image: sha2121/shophub-cart:amd-v1
    container_name: shophub_cart
    restart: unless-stopped
    environment:
      PORT: 3002
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3002:3002"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - shophub_network

  checkout-service:
    image: sha2121/shophub-checkout:amd-v1
    container_name: shophub_checkout
    restart: unless-stopped
    environment:
      PORT: 3003
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: shophub_user
      DB_PASSWORD: shophub_pass
      DB_NAME: shophub
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBIT_URL: amqp://rabbitmq
    ports:
      - "3003:3003"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - shophub_network

networks:
  shophub_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
